package com.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * FileManagerService service = new FileManagerService();
 * FileManagerDelegate portType = service.getFileManagerPort();
 * portType.addFileInfo(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "FileManagerService", targetNamespace = "http://action.sample.com/", wsdlLocation = "http://127.0.0.1:8080/webServiceSample/FileManagerPort?wsdl")
public class FileManagerService extends Service {

	private final static URL FILEMANAGERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.client.FileManagerService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.client.FileManagerService.class.getResource(".");
			url = new URL(baseUrl,
					"http://127.0.0.1:8080/webServiceSample/FileManagerPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/webServiceSample/FileManagerPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		FILEMANAGERSERVICE_WSDL_LOCATION = url;
	}

	public FileManagerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FileManagerService() {
		super(FILEMANAGERSERVICE_WSDL_LOCATION, new QName(
				"http://action.sample.com/", "FileManagerService"));
	}

	/**
	 * 
	 * @return returns FileManagerDelegate
	 */
	@WebEndpoint(name = "FileManagerPort")
	public FileManagerDelegate getFileManagerPort() {
		return super.getPort(new QName("http://action.sample.com/",
				"FileManagerPort"), FileManagerDelegate.class);
	}

}
